name: Sugestão
description: Ideia de funcionalidade ou melhoria
labels: [enhancement]
body:
  - type: textarea
    id: problema
    attributes:
      label: Qual problema isso resolve?
    validations:
      required: true
  - type: textarea
    id: solucao
    attributes:
      label: Como você imagina a solução?
